CLASS zcl_segunda_clase_00 DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    METHODS saludar.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_SEGUNDA_CLASE_00 IMPLEMENTATION.


  METHOD saludar.
    DATA lv_saludo TYPE string.
    lv_saludo = 'Hola'.
  ENDMETHOD.
ENDCLASS.
